### ISSUE TITLE
for when version 1.12.2?

### ISSUE THREAD

**Issue by JoShMiQueL** [N3ROO/Bettercolors#46]

**Comment by N3ROO** [comment]
It was not planned but if some people want it I can code it by taking the MC1.8.9 features. I wanted to code some stuff tomorrow, I guess that I found something to do :)
If I am fast enough **it should be released by sunday night tomorrow (US WEST)**

I will also work on the 1.14.4 version so that I will be able to work on the 1.15.2 one the next week.

Thanks for your interest :)

**Comment by N3ROO** [comment]
@JoShMiQueL 
I released Bettercolors for Minecraft 1.12.2. It contains all the features of the most advanced version (1.8.9).
See: [Bettercolors 6.1.0 for MC1.12.2 release page](https://github.com/N3ROO/Bettercolors/releases/tag/6.1.0-MC1.12.2)
