### ISSUE TITLE
hotkey toggle for triggerbot

### ISSUE THREAD

**Issue by OverheadOcean** [N3ROO/Bettercolors#62]

**Comment by N3ROO** [comment]
This is planned :). In the 7.3.0 version you will be able to change the toggle key for each module. I'm currently updating the engine to 1.0.0 ([engine progress here](https://github.com/N3ROO/BettercolorsEngine/projects/4)). Then, I'll need to update the mod to work with the new engine ([mod progress here](https://github.com/N3ROO/Bettercolors/projects/17)).

I hope that the forge team will release the 1.16.2 version fast enough, because I want the 7.3.0 to be released on the 1.16.2 and not 1.16.1. Either way, the fabric version will be updated first (fabric is better and faster than forge :p).

**Comment by N3ROO** [comment]
Done for MC1.16.2 (forge) https://github.com/N3ROO/Bettercolors/releases/tag/7.3.0-MC1.16.2
