### ISSUE TITLE
1.16.2 Initialization Crash - Fabric

### ISSUE THREAD

**Issue by lostsys** [N3ROO/Bettercolors#63]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mcp'!

Reproduction:
Starting up minecraft with said requirements leads to this crash

Mods Folder:
Bettercolors - Fabric 1.16.2 from Github Assets Release
Fabric API 0.17.2 build.396 - 1.16.2

Fabric Launcher Version:
fabric loader- 0.9.1 build.205 - 1.16.2

**Comment by N3ROO** [comment]
Thank you for your report, I'll investigate this issue right away

**Comment by N3ROO** [comment]
A dependency was not included in the .jar file. But it was working for me because I add the dependency in my mods/ folders. I just updated the .jar file to include that dependency. You can download it now, it works. Sorry for the inconvenience

https://github.com/N3ROO/Bettercolors/releases/tag/7.2.0-MC1.16.2fa

**Comment by lostsys** [comment]
Thanks so much, love your work

**Comment by N3ROO** [comment]
No problem! Don't hesitate to open an issue to request new features and stuff 😁
