### ISSUE TITLE
Linux Issue with menu

### ISSUE THREAD

**Issue by wieisstimpee** [N3ROO/Bettercolors#64]
Hello, I am using Linux Mint en when I press insert the menu doesn't appear and my game crashes.
I am using the Minecraft 1.8.9 version 7.1.0.
Thanks for all the work you've done so far.

**Comment by N3ROO** [comment]
Hey, thanks for your report! Do you mind sending your crash report? It should be located under the crash-reports/ directory that is in the minecraft installation folder.

![image](https://user-images.githubusercontent.com/26824108/90369571-4d86ef80-e06c-11ea-8609-fa18d2dc081a.png)

**Comment by wieisstimpee** [comment]
[crash-2020-08-17_08.39.25-client.txt](https://github.com/N3ROO/Bettercolors/files/5083221/crash-2020-08-17_08.39.25-client.txt)
Thanks for your quick reply, here you go!

**Comment by N3ROO** [comment]
According to your crash report, for some reason, in your .jar file you did not have the "mdlaf" folder. I also found an other issue with Linux (Mint 20.0) where the window would hang when turning the GUI on. Everything should be fixed by now. Thanks for your report! Don't hesitate to re-open the issue if it does not work for you.

I used:
- Linux Mint 20.0
- OpenJdk/Jre 8 (`/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java`)

You can download the new .jar file here: https://github.com/N3ROO/Bettercolors/releases/tag/7.1.0-MC1.8.9

**Comment by wieisstimpee** [comment]
It seems to be fixed now, thanks again!
