### ISSUE TITLE
Speed bridging mod

### ISSUE THREAD

**Issue by lolgamergotaids** [N3ROO/Bettercolors#72]
**Is your feature request related to a problem? Please describe.** no
A clear and concise description of what the problem is. Ex. I'm always frustrated when [nothing]

**Describe the solution you'd like**
A bedwars speed bridging mod like auto crouch and uncrouch
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered 

**Additional context**
Nothing else thank you :)

**Comment by N3ROO** [comment]
Hey @lolgamergotaids what would be a good behavior for the speed bridging module (knowing that this mod is supposed to look legit)? Should it be something that places blocks as fast as possible?

**Comment by lolgamergotaids** [comment]
Yeah and maybe like add different modes like breezily bridging and speed bridging and god bridging if possible would be great

**Comment by N3ROO** [comment]
- Breezily bridging: sounds a bit complicated because the module needs to move your character, and I don't really like modules that automate your behavior (may not look legit in some cases)
- Speed bridging: That one should be okay, it just needs to shift your character just after placing a block (place block, run for like 50 ms, then shift, then place block, ....). You, the player, will have to move in the right direction and the module will place blocks and shift for you. It will need an hotkey to be turned on and off.
- God bridging: you have to place yourself in the right position first, a module can't do that for you. But it can click as fast as possible

For breezily bridging and god bridging, I'll add a right click auto clicker (see #75 ). That module may be useful in some other cases as well

**Comment by lolgamergotaids** [comment]
And i forgot diagonal bridging if you can do that too it will be great

**Comment by N3ROO** [comment]
Done for MC1.16.4 (forge): https://github.com/N3ROO/Bettercolors/releases/tag/7.4.0-MC1.16.4

**Comment by N3ROO** [comment]
done for the other versions as well
