### ISSUE TITLE
Click sound

### ISSUE THREAD

**Issue by ulashx** [N3ROO/Bettercolors#77]
It would be nice if you could add a click sound to the program like jitter click sound

**Comment by N3ROO** [comment]
That's a good request, yeah sure!

**Comment by N3ROO** [comment]
after working a while on it, it turns out that I won't be implementing this feature for few reasons:
- You can clearly tell the difference between the fake mouse click and your mouse click (everyone has a different sound according to their microphone, mouse, position relative to the mouse and so on)
- It's a mess to play sounds in java
