### ISSUE TITLE
Forge 1.16.4 Not Working

### ISSUE THREAD

**Issue by genericgithubaccount1** [N3ROO/Bettercolors#86]
I'm using forge 1.16.4. 
I've pressed INSERT, yet the menu won't open and my character continually shifts up and down.
I don't know what I'm doing wrong, I would be grateful if you told me how to fix this.
Thanks!

- **Have you tried running the mod using the option debug=true**: yes / no
- **Have you tried deleting the config files? (minecraft/config/bc_filename.properties)**: yes / no

**Comment by N3ROO** [comment]
> my character continually shifts up and down

On fresh installations, it sounds like speed bridging is enabled by default. I'll fix that asap.

> I've pressed INSERT, yet the menu won't open

It works well for me. If it's not the first time that you use Bettercolors, check the config file at `your_minecraft_dir/config/bc_default.properties`, and check the value of "toggle_key" it should be set at 260 (which is the INSERT key). If you want to change the key manually, here is a link with all the keys available: https://www.glfw.org/docs/3.3/group__keys.html

Otherwise, if you want Bettercolors to open the GUI by defaul, change `debug=false` to `debug=true` in `bc_default.properties`. You will be able to change the toggle key in the GUI (in keybinds -> GUI toggle key).

**Comment by genericgithubaccount1** [comment]
yup, worked fine. just didnt expect the mod to be 'external' if that makes sense. would be cool to see the triggerbot work a bit better with 1.9 pvp and maybe the ability to bind modules to mouse buttons. other than that, rlly solid mod

**Comment by N3ROO** [comment]
it's nice to hear

> would be cool to see the triggerbot work a bit better with 1.9 pvp

I don't think that I'll port the mod to 1.9 because a lot of things changed. But who knows, I may port it at some point :p

> maybe the ability to bind modules to mouse buttons

that's a nice idea!
